package webservice.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-09T21:57:57.097+01:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://test.webservice/", name = "WSTest")
@XmlSeeAlso({ObjectFactory.class})
public interface WSTest {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "echoNoAuth", targetNamespace = "http://test.webservice/", className = "webservice.test.EchoNoAuth")
    @WebMethod
    @ResponseWrapper(localName = "echoNoAuthResponse", targetNamespace = "http://test.webservice/", className = "webservice.test.EchoNoAuthResponse")
    public java.lang.String echoNoAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://test.webservice/", className = "webservice.test.Echo")
    @WebMethod
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://test.webservice/", className = "webservice.test.EchoResponse")
    public java.lang.String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
